/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolSlugIndexRouteImport } from './routes/$schoolSlug/index'
import { Route as AuthenticatedSuperRouteImport } from './routes/_authenticated/super'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as SchoolSlugAnnouncementsRouteImport } from './routes/$schoolSlug/announcements'
import { Route as AuthenticatedManageSchoolSlugRouteImport } from './routes/_authenticated/manage.$schoolSlug'
import { Route as SchoolSlugResultsStudentIdRouteImport } from './routes/$schoolSlug/results.$studentId'
import { Route as AuthenticatedManageSchoolSlugIndexRouteImport } from './routes/_authenticated/manage.$schoolSlug.index'
import { Route as AuthenticatedManageSchoolSlugStudentsRouteImport } from './routes/_authenticated/manage.$schoolSlug.students'
import { Route as AuthenticatedManageSchoolSlugSettingsRouteImport } from './routes/_authenticated/manage.$schoolSlug.settings'
import { Route as AuthenticatedManageSchoolSlugExamsRouteImport } from './routes/_authenticated/manage.$schoolSlug.exams'
import { Route as AuthenticatedManageSchoolSlugAnnouncementsRouteImport } from './routes/_authenticated/manage.$schoolSlug.announcements'
import { Route as AuthenticatedManageSchoolSlugAcademicsRouteImport } from './routes/_authenticated/manage.$schoolSlug.academics'
import { Route as AuthenticatedManageSchoolSlugExamsExamIdRouteImport } from './routes/_authenticated/manage.$schoolSlug.exams.$examId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolSlugIndexRoute = SchoolSlugIndexRouteImport.update({
  id: '/$schoolSlug/',
  path: '/$schoolSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperRoute = AuthenticatedSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SchoolSlugAnnouncementsRoute = SchoolSlugAnnouncementsRouteImport.update({
  id: '/$schoolSlug/announcements',
  path: '/$schoolSlug/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManageSchoolSlugRoute =
  AuthenticatedManageSchoolSlugRouteImport.update({
    id: '/manage/$schoolSlug',
    path: '/manage/$schoolSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SchoolSlugResultsStudentIdRoute =
  SchoolSlugResultsStudentIdRouteImport.update({
    id: '/$schoolSlug/results/$studentId',
    path: '/$schoolSlug/results/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedManageSchoolSlugIndexRoute =
  AuthenticatedManageSchoolSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManageSchoolSlugRoute,
  } as any)
const AuthenticatedManageSchoolSlugStudentsRoute =
  AuthenticatedManageSchoolSlugStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedManageSchoolSlugRoute,
  } as any)
const AuthenticatedManageSchoolSlugSettingsRoute =
  AuthenticatedManageSchoolSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedManageSchoolSlugRoute,
  } as any)
const AuthenticatedManageSchoolSlugExamsRoute =
  AuthenticatedManageSchoolSlugExamsRouteImport.update({
    id: '/exams',
    path: '/exams',
    getParentRoute: () => AuthenticatedManageSchoolSlugRoute,
  } as any)
const AuthenticatedManageSchoolSlugAnnouncementsRoute =
  AuthenticatedManageSchoolSlugAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedManageSchoolSlugRoute,
  } as any)
const AuthenticatedManageSchoolSlugAcademicsRoute =
  AuthenticatedManageSchoolSlugAcademicsRouteImport.update({
    id: '/academics',
    path: '/academics',
    getParentRoute: () => AuthenticatedManageSchoolSlugRoute,
  } as any)
const AuthenticatedManageSchoolSlugExamsExamIdRoute =
  AuthenticatedManageSchoolSlugExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedManageSchoolSlugExamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/$schoolSlug/announcements': typeof SchoolSlugAnnouncementsRoute
  '/app': typeof AuthenticatedAppRoute
  '/super': typeof AuthenticatedSuperRoute
  '/$schoolSlug/': typeof SchoolSlugIndexRoute
  '/$schoolSlug/results/$studentId': typeof SchoolSlugResultsStudentIdRoute
  '/manage/$schoolSlug': typeof AuthenticatedManageSchoolSlugRouteWithChildren
  '/manage/$schoolSlug/academics': typeof AuthenticatedManageSchoolSlugAcademicsRoute
  '/manage/$schoolSlug/announcements': typeof AuthenticatedManageSchoolSlugAnnouncementsRoute
  '/manage/$schoolSlug/exams': typeof AuthenticatedManageSchoolSlugExamsRouteWithChildren
  '/manage/$schoolSlug/settings': typeof AuthenticatedManageSchoolSlugSettingsRoute
  '/manage/$schoolSlug/students': typeof AuthenticatedManageSchoolSlugStudentsRoute
  '/manage/$schoolSlug/': typeof AuthenticatedManageSchoolSlugIndexRoute
  '/manage/$schoolSlug/exams/$examId': typeof AuthenticatedManageSchoolSlugExamsExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/$schoolSlug/announcements': typeof SchoolSlugAnnouncementsRoute
  '/app': typeof AuthenticatedAppRoute
  '/super': typeof AuthenticatedSuperRoute
  '/$schoolSlug': typeof SchoolSlugIndexRoute
  '/$schoolSlug/results/$studentId': typeof SchoolSlugResultsStudentIdRoute
  '/manage/$schoolSlug/academics': typeof AuthenticatedManageSchoolSlugAcademicsRoute
  '/manage/$schoolSlug/announcements': typeof AuthenticatedManageSchoolSlugAnnouncementsRoute
  '/manage/$schoolSlug/exams': typeof AuthenticatedManageSchoolSlugExamsRouteWithChildren
  '/manage/$schoolSlug/settings': typeof AuthenticatedManageSchoolSlugSettingsRoute
  '/manage/$schoolSlug/students': typeof AuthenticatedManageSchoolSlugStudentsRoute
  '/manage/$schoolSlug': typeof AuthenticatedManageSchoolSlugIndexRoute
  '/manage/$schoolSlug/exams/$examId': typeof AuthenticatedManageSchoolSlugExamsExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/$schoolSlug/announcements': typeof SchoolSlugAnnouncementsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/super': typeof AuthenticatedSuperRoute
  '/$schoolSlug/': typeof SchoolSlugIndexRoute
  '/$schoolSlug/results/$studentId': typeof SchoolSlugResultsStudentIdRoute
  '/_authenticated/manage/$schoolSlug': typeof AuthenticatedManageSchoolSlugRouteWithChildren
  '/_authenticated/manage/$schoolSlug/academics': typeof AuthenticatedManageSchoolSlugAcademicsRoute
  '/_authenticated/manage/$schoolSlug/announcements': typeof AuthenticatedManageSchoolSlugAnnouncementsRoute
  '/_authenticated/manage/$schoolSlug/exams': typeof AuthenticatedManageSchoolSlugExamsRouteWithChildren
  '/_authenticated/manage/$schoolSlug/settings': typeof AuthenticatedManageSchoolSlugSettingsRoute
  '/_authenticated/manage/$schoolSlug/students': typeof AuthenticatedManageSchoolSlugStudentsRoute
  '/_authenticated/manage/$schoolSlug/': typeof AuthenticatedManageSchoolSlugIndexRoute
  '/_authenticated/manage/$schoolSlug/exams/$examId': typeof AuthenticatedManageSchoolSlugExamsExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/$schoolSlug/announcements'
    | '/app'
    | '/super'
    | '/$schoolSlug/'
    | '/$schoolSlug/results/$studentId'
    | '/manage/$schoolSlug'
    | '/manage/$schoolSlug/academics'
    | '/manage/$schoolSlug/announcements'
    | '/manage/$schoolSlug/exams'
    | '/manage/$schoolSlug/settings'
    | '/manage/$schoolSlug/students'
    | '/manage/$schoolSlug/'
    | '/manage/$schoolSlug/exams/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/$schoolSlug/announcements'
    | '/app'
    | '/super'
    | '/$schoolSlug'
    | '/$schoolSlug/results/$studentId'
    | '/manage/$schoolSlug/academics'
    | '/manage/$schoolSlug/announcements'
    | '/manage/$schoolSlug/exams'
    | '/manage/$schoolSlug/settings'
    | '/manage/$schoolSlug/students'
    | '/manage/$schoolSlug'
    | '/manage/$schoolSlug/exams/$examId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/$schoolSlug/announcements'
    | '/_authenticated/app'
    | '/_authenticated/super'
    | '/$schoolSlug/'
    | '/$schoolSlug/results/$studentId'
    | '/_authenticated/manage/$schoolSlug'
    | '/_authenticated/manage/$schoolSlug/academics'
    | '/_authenticated/manage/$schoolSlug/announcements'
    | '/_authenticated/manage/$schoolSlug/exams'
    | '/_authenticated/manage/$schoolSlug/settings'
    | '/_authenticated/manage/$schoolSlug/students'
    | '/_authenticated/manage/$schoolSlug/'
    | '/_authenticated/manage/$schoolSlug/exams/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  SchoolSlugAnnouncementsRoute: typeof SchoolSlugAnnouncementsRoute
  SchoolSlugIndexRoute: typeof SchoolSlugIndexRoute
  SchoolSlugResultsStudentIdRoute: typeof SchoolSlugResultsStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$schoolSlug/': {
      id: '/$schoolSlug/'
      path: '/$schoolSlug'
      fullPath: '/$schoolSlug/'
      preLoaderRoute: typeof SchoolSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$schoolSlug/announcements': {
      id: '/$schoolSlug/announcements'
      path: '/$schoolSlug/announcements'
      fullPath: '/$schoolSlug/announcements'
      preLoaderRoute: typeof SchoolSlugAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manage/$schoolSlug': {
      id: '/_authenticated/manage/$schoolSlug'
      path: '/manage/$schoolSlug'
      fullPath: '/manage/$schoolSlug'
      preLoaderRoute: typeof AuthenticatedManageSchoolSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$schoolSlug/results/$studentId': {
      id: '/$schoolSlug/results/$studentId'
      path: '/$schoolSlug/results/$studentId'
      fullPath: '/$schoolSlug/results/$studentId'
      preLoaderRoute: typeof SchoolSlugResultsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manage/$schoolSlug/': {
      id: '/_authenticated/manage/$schoolSlug/'
      path: '/'
      fullPath: '/manage/$schoolSlug/'
      preLoaderRoute: typeof AuthenticatedManageSchoolSlugIndexRouteImport
      parentRoute: typeof AuthenticatedManageSchoolSlugRoute
    }
    '/_authenticated/manage/$schoolSlug/students': {
      id: '/_authenticated/manage/$schoolSlug/students'
      path: '/students'
      fullPath: '/manage/$schoolSlug/students'
      preLoaderRoute: typeof AuthenticatedManageSchoolSlugStudentsRouteImport
      parentRoute: typeof AuthenticatedManageSchoolSlugRoute
    }
    '/_authenticated/manage/$schoolSlug/settings': {
      id: '/_authenticated/manage/$schoolSlug/settings'
      path: '/settings'
      fullPath: '/manage/$schoolSlug/settings'
      preLoaderRoute: typeof AuthenticatedManageSchoolSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedManageSchoolSlugRoute
    }
    '/_authenticated/manage/$schoolSlug/exams': {
      id: '/_authenticated/manage/$schoolSlug/exams'
      path: '/exams'
      fullPath: '/manage/$schoolSlug/exams'
      preLoaderRoute: typeof AuthenticatedManageSchoolSlugExamsRouteImport
      parentRoute: typeof AuthenticatedManageSchoolSlugRoute
    }
    '/_authenticated/manage/$schoolSlug/announcements': {
      id: '/_authenticated/manage/$schoolSlug/announcements'
      path: '/announcements'
      fullPath: '/manage/$schoolSlug/announcements'
      preLoaderRoute: typeof AuthenticatedManageSchoolSlugAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedManageSchoolSlugRoute
    }
    '/_authenticated/manage/$schoolSlug/academics': {
      id: '/_authenticated/manage/$schoolSlug/academics'
      path: '/academics'
      fullPath: '/manage/$schoolSlug/academics'
      preLoaderRoute: typeof AuthenticatedManageSchoolSlugAcademicsRouteImport
      parentRoute: typeof AuthenticatedManageSchoolSlugRoute
    }
    '/_authenticated/manage/$schoolSlug/exams/$examId': {
      id: '/_authenticated/manage/$schoolSlug/exams/$examId'
      path: '/$examId'
      fullPath: '/manage/$schoolSlug/exams/$examId'
      preLoaderRoute: typeof AuthenticatedManageSchoolSlugExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedManageSchoolSlugExamsRoute
    }
  }
}

interface AuthenticatedManageSchoolSlugExamsRouteChildren {
  AuthenticatedManageSchoolSlugExamsExamIdRoute: typeof AuthenticatedManageSchoolSlugExamsExamIdRoute
}

const AuthenticatedManageSchoolSlugExamsRouteChildren: AuthenticatedManageSchoolSlugExamsRouteChildren =
  {
    AuthenticatedManageSchoolSlugExamsExamIdRoute:
      AuthenticatedManageSchoolSlugExamsExamIdRoute,
  }

const AuthenticatedManageSchoolSlugExamsRouteWithChildren =
  AuthenticatedManageSchoolSlugExamsRoute._addFileChildren(
    AuthenticatedManageSchoolSlugExamsRouteChildren,
  )

interface AuthenticatedManageSchoolSlugRouteChildren {
  AuthenticatedManageSchoolSlugAcademicsRoute: typeof AuthenticatedManageSchoolSlugAcademicsRoute
  AuthenticatedManageSchoolSlugAnnouncementsRoute: typeof AuthenticatedManageSchoolSlugAnnouncementsRoute
  AuthenticatedManageSchoolSlugExamsRoute: typeof AuthenticatedManageSchoolSlugExamsRouteWithChildren
  AuthenticatedManageSchoolSlugSettingsRoute: typeof AuthenticatedManageSchoolSlugSettingsRoute
  AuthenticatedManageSchoolSlugStudentsRoute: typeof AuthenticatedManageSchoolSlugStudentsRoute
  AuthenticatedManageSchoolSlugIndexRoute: typeof AuthenticatedManageSchoolSlugIndexRoute
}

const AuthenticatedManageSchoolSlugRouteChildren: AuthenticatedManageSchoolSlugRouteChildren =
  {
    AuthenticatedManageSchoolSlugAcademicsRoute:
      AuthenticatedManageSchoolSlugAcademicsRoute,
    AuthenticatedManageSchoolSlugAnnouncementsRoute:
      AuthenticatedManageSchoolSlugAnnouncementsRoute,
    AuthenticatedManageSchoolSlugExamsRoute:
      AuthenticatedManageSchoolSlugExamsRouteWithChildren,
    AuthenticatedManageSchoolSlugSettingsRoute:
      AuthenticatedManageSchoolSlugSettingsRoute,
    AuthenticatedManageSchoolSlugStudentsRoute:
      AuthenticatedManageSchoolSlugStudentsRoute,
    AuthenticatedManageSchoolSlugIndexRoute:
      AuthenticatedManageSchoolSlugIndexRoute,
  }

const AuthenticatedManageSchoolSlugRouteWithChildren =
  AuthenticatedManageSchoolSlugRoute._addFileChildren(
    AuthenticatedManageSchoolSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedSuperRoute: typeof AuthenticatedSuperRoute
  AuthenticatedManageSchoolSlugRoute: typeof AuthenticatedManageSchoolSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedSuperRoute: AuthenticatedSuperRoute,
  AuthenticatedManageSchoolSlugRoute:
    AuthenticatedManageSchoolSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  SchoolSlugAnnouncementsRoute: SchoolSlugAnnouncementsRoute,
  SchoolSlugIndexRoute: SchoolSlugIndexRoute,
  SchoolSlugResultsStudentIdRoute: SchoolSlugResultsStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
